import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'tr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  translatePosition: (position: string) => string;
  formatDate: (date: Date) => string;
  languageSelected: boolean;
  setLanguageSelected: (selected: boolean) => void;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Language Selection
    'selectLanguage': 'Select Language',
    'english': 'English',
    'turkish': 'Turkish',
    'continue': 'Continue',
    
    // Career Selection
    'selectCareerSlot': 'Select Career Slot',
    'chooseSlot': 'Choose a slot to start or continue your career',
    'slot': 'Slot',
    'empty': 'Empty',
    'lastPlayed': 'Last played',
    'deleteCareer': 'Delete Career?',
    'deleteCareerConfirm': 'This career will be permanently deleted. Are you sure you want to continue?',
    'cancel': 'Cancel',
    'delete': 'Delete',
    
    // Main Menu
    'mainMenu': 'MAIN MENU',
    'welcome': 'Welcome',
    'teamManagement': 'TEAM MANAGEMENT',
    'squad': 'Squad',
    'rosterView': 'Roster View',
    'viewAndManage': 'View and manage your squad',
    'formationView': 'Formation View',
    'startingXI': 'Starting XI and tactics',
    'financialTable': 'Financial Table',
    'incomeExpenses': 'Income, expenses, and budget',
    'clubManagement': 'Club Management',
    'club': 'Club',
    'favorites': 'Favorites',
    'favoritesTitle': 'FAVORITES',
    'trackPlayers': 'Track your favorite players',
    'trackPlayersDescription': 'Track your favorite players across the league.',
    'totalFavorites': 'Total Favorites',
    'noFavoritePlayersYet': 'No favorite players yet. Add players to your favorites from the Transfer Market or other teams.',
    'remove': 'Remove',
    'freeAgent': 'Free Agent',
    'transfers': 'Transfers',
    'transferMarket': 'Transfer Market',
    'browsePlayers': 'Browse available players',
    'leagueHub': 'LEAGUE HUB',
    'leagueHubCard': 'League Hub',
    'standingsResults': 'Standings, Results, Stats & Fixtures',
    'transferOfferTitle': 'Transfer Offer',
    'loanOfferTitle': 'Loan Offer',
    'expires': 'Expires',
    'negotiationRound': 'Negotiation Round',
    'waitingForResponse': 'Waiting for response...',
    'counterReviewNextWeek': 'Your counter offer will be reviewed next week.',
    'later': 'Later',
    'offerHistory': 'Offer History',
    'initialOffer': 'Initial Offer',
    'roundLabel': 'Round {round}',
    'historyNoteInitial': 'Initial offer',
    'historyNoteCounter': 'Counter offer',
    'historyNoteAccepted': 'Accepted counter offer',
    'historyNoteRejected': 'Offer rejected',
    'counterOfferTitle': 'Counter Offer',
    'currentOffer': 'Current Offer',
    'makeCounterOffer': 'Make Counter Offer',
    'rotateDevice': 'Rotate Your Device',
    'rotateDeviceMessage': 'Please rotate your device to landscape mode to play the game.',
    'rotateDeviceSubmessage': 'The game requires a horizontal screen orientation.',
    'minLabel': 'Min',
    'originalLabel': 'Original',
    'maxLabel': 'Max',
    'sendCounterOffer': 'Send Counter Offer',
    'responseNextWeek': 'Response will come next week',
    'mailboxTitle': 'Mailbox',
    'mailboxMenuDescription': 'All notifications & news',
    'mailboxEmptyTitle': 'Quiet mailbox',
    'mailboxEmptyDescription': 'All important updates, transfer results, and negotiations will appear here.',
    'markAllRead': 'Mark all read',
    'clearAll': 'Clear all',
    'markRead': 'Mark read',
    'markUnread': 'Mark unread',
    'unread': 'unread',
    'noMessages': 'No messages yet',
    
    // Common
    'exitToCareerSelect': 'Exit to Career Select',
    'save': 'Save',
    'gameSaved': 'Game saved successfully!',
    'noSaveData': 'No saved data found for this slot.',
    'loadError': 'Failed to load career. Please try again.',
    'back': 'Back',
    // Shop
    'shop': 'Shop',
    'shopDescription': 'Purchase boosts and upgrades for your team',
    'shopMenuDescription': 'Purchase boosts and upgrades',
    'shopItems': 'Shop Items',
    'legendaryPlayers': 'Legendary Players',
    'legendaryPack': 'Legendary Player Pack',
    'legendaryPackDesc': 'Draw a legendary player (90+ rating)',
    'premiumPack': 'Premium Pack',
    'elitePack': 'Elite Pack',
    'standardPack': 'Standard Pack',
    'selectPack': 'Select Pack',
    'premiumTickets': 'Premium Tickets',
    'ticket': 'Ticket',
    'ticketUsed': 'Premium ticket used!',
    'noPremiumTickets': 'No premium tickets! Win trophies to earn tickets.',
    'dropRates': 'Drop Rates',
    'legendary': 'LEGENDARY',
    'epic': 'EPIC',
    'rare': 'RARE',
    'common': 'COMMON',
    'drawing': 'Drawing...',
    'drawPlayer': 'Draw Player',
    'openingPack': 'Opening Pack...',
    'close': 'Close',
    'addToTeam': 'Add to Team',
    'drawAgain': 'Draw Again',
    'addedToTeam': 'added to team',
    'squadSizeLimitReached': 'Squad size limit reached! You must sell a player first.',
    'tapToOpen': 'TAP TO OPEN',
    'charging': 'CHARGING...',
    'clickToPurchase': 'Click to Purchase',
    // Player Stats
    'pac': 'PAC',
    'sho': 'SHO',
    'pas': 'PAS',
    'dri': 'DRI',
    'def': 'DEF',
    'phy': 'PHY',
    // Goalkeeper Stats
    'div': 'DIV',
    'han': 'HAN',
    'kic': 'KIC',
    'ref': 'REF',
    'spd': 'SPD',
    'gkPos': 'POS',
    'boosts': 'Boosts',
    'upgrades': 'Upgrades',
    'special': 'Special',
    'boost': 'Boost',
    'upgrade': 'Upgrade',
    'price': 'Price',
    'buy': 'Buy',
    'purchaseSuccess': 'Purchase successful!',
    'insufficientFunds': 'Insufficient funds!',
    'trainingBoost': 'Training Boost',
    'trainingBoostDesc': 'Increase player development rate by 20% for 1 month',
    'scoutBoost': 'Scout Boost',
    'scoutBoostDesc': 'Reduce scouting time by 50% for next 3 scouts',
    'fitnessBoost': 'Fitness Boost',
    'fitnessBoostDesc': 'Reduce injury risk by 30% for 1 month',
    'facilityUpgrade': 'Training Facility Upgrade',
    'facilityUpgradeDesc': 'Permanently improve training facilities (+5% player development)',
    'medicalUpgrade': 'Medical Center Upgrade',
    'medicalUpgradeDesc': 'Permanently reduce injury recovery time by 25%',
    'youthFacility': 'Youth Academy Upgrade',
    'youthFacilityDesc': 'Improve youth academy quality (+10% better prospects)',
    'transferBoost': 'Transfer Window Boost',
    'transferBoostDesc': 'Increase transfer negotiation success rate by 15%',
    'fanBoost': 'Fan Morale Boost',
    'fanBoostDesc': 'Instantly increase fan morale by 10 points',
    // Match Screen
    'matchFeed': 'Match Feed',
    'live': 'LIVE',
    'waitingForKickoff': 'Waiting for kickoff...',
    'matchFinished': 'MATCH FINISHED',
    'liveMatchday': 'LIVE MATCHDAY',
    'continueMatch': 'CONTINUE',
    'home': 'Home',
    'away': 'Away',
    'matchStats': 'Match Stats',
    'matches': 'Matches',
    'shots': 'Shots',
    'Possession': 'Possession',
    'assistantManager': 'Assistant Manager',
    'askAdvice': 'Ask Advice',
    'thinking': 'Thinking...',
    'assistantWatching': "I'm watching the game, boss. Ask me if you need tactical input.",
    // Loading Messages
    'loadingCareer': 'Loading career...',
    'initializingDatabase': 'Initializing Premier League Database...',
    'negotiatingContract': 'Negotiating contract with {teamName}...',
    'scoutingPlayers': 'Scouting players for {teamName}...',
    'simulatingDeadlineDay': 'Simulating Deadline Day & CPU Transfers...',
    'simulatingRemainder': 'Simulating remainder of the season...',
    'finalizingPreSeason': 'Finalizing Pre-Season Preparations...',
    'pause': 'PAUSE',
    'resume': 'RESUME',
    'finishMatch': 'FINISH MATCH',
    'returnToMenu': 'Return to Menu',
    'goalFor': 'Goal for',
    'fullTime': "FULL TIME! The referee blows the final whistle.",
    'welcomeMatch': "Welcome to today's match! {homeTeam} vs {awayTeam}. The atmosphere is electric.",
    'playerPerformances': 'Player Performances',
    'performanceDataNotAvailable': 'Performance data not available for this match.',
    'matchIntroTitle': 'Match Preview',
    'matchIntroSubtitle': '{homeTeam} vs {awayTeam}',
    'matchIntroDetails': '{competition} • Week {weekNumber}',
    'startMatch': 'Start Match',
    'versus': 'VS',
    'referee': 'Referee',
    'kickoff': 'Kickoff',
    'firstHalf': 'First Half',
    'secondHalf': 'Second Half',
    'halftime': 'Half Time',
    'resumeMatch': 'Resume Match',
    'matchSummary': 'Match Summary',
    'homeTeam': 'Home Team',
    'awayTeam': 'Away Team',
    'possession': 'Possession',
    'shotsOnTarget': 'Shots on Target',
    'corners': 'Corners',
    'fouls': 'Fouls',
    'yellowCards': 'Yellow Cards',
    'redCards': 'Red Cards',
    'speed1x': '1x Speed',
    'speed3x': '3x Speed',
    'skipToEnd': 'Skip to End',
    'skip': 'Skip',
    'player': 'Player',
    'goals': 'Goals',
    'assists': 'Assists',
    'assistLabel': 'Assist',
    'ratingHeader': 'Rating',
    'halfTimeTitle': 'Half Time',
    'halfTimeResumeIn': 'Match will continue in',
    'seconds': 'seconds',
    'week': 'Week',
    // Team Selection
    'selectClub': 'SELECT CLUB',
    'chooseYourLegacy': 'Choose your legacy.',
    'budget': 'Budget',
    'backToTeams': 'Back to Teams',
    'startingBudget': 'Starting Budget',
    'players': 'Players',
    'formation': 'Formation',
    'attackRating': 'Attack Rating',
    'defenseRating': 'Defense Rating',
    'midfieldRating': 'Midfield Rating',
    'overallRating': 'Overall Rating',
    'fullSquad': 'Full Squad',
    'startingXIAndTactics': 'Starting XI and Tactics',
    'opponentSquad': 'Opponent Squad',
    'scout': 'Scout',
    'scouting': 'Scouting...',
    'approach': 'Approach',
    'view': 'View',
    // Stadium Expansion
    'expandStadium': 'Expand Stadium',
    'startExpansion': 'Start Expansion',
    'weeks': 'weeks',
    // Match Detail Modal
    'matchweek': 'Matchweek',
    'stadium': 'Stadium',
    'manOfTheMatch': 'Man of the Match',
    'manOfTheMatchAuto': 'Man of the Match will be automatically selected after the match.',
    'premierLeague': 'Premier League',
    // Overall Rating
    'overallRatingShort': 'OVR',
    // Captain
    'captain': 'Captain',
    'setAsCaptain': 'Set as Captain',
    'currentCaptain': 'Current Captain',
    'simWeek': 'SIM WEEK',
    'simSeason': 'SIM SEASON',
    'takeControl': 'TAKE CONTROL',
    'youthAcademy': 'Youth Academy',
    'scoutYouthPlayers': 'Scout and sign youth players',
    'futureStars': 'FUTURE STARS',
    'noScoutingMissionActive': 'No Scouting Mission Active',
    'scoutMissionDescription': 'Send your youth scouts to local academies to find the next generation of talent.',
    'thisWillCost': 'This will cost',
    'startScoutingMission': 'START SCOUTING MISSION',
    'reload': 'Reload',
    'promote': 'PROMOTE',
    'noProspectsFound': 'No prospects found.',
    'noMoreProspects': 'No more prospects available from this batch.',
    'reloadScouting': 'RELOAD SCOUTING',
    'contractNegotiation': 'Contract Negotiation',
    'demand': 'Demand',
    'reaction': 'Reaction',
    'shortTermHigherWage': 'Short term (Higher Wage)',
    'longTermLowerWage': 'Long term (Lower Wage)',
    'dealAgreed': 'Deal Agreed!',
    'negotiationFailed': 'Negotiation Failed',
    'signedFor': 'Signed for',
    'playerRejectedTerms': 'Player rejected your terms.',
    'welcomeToTheClub': 'WELCOME TO THE CLUB',
    'worldClass': '💎 WORLD CLASS',
    'elite': '🌟 ELITE',
    'topTier': '✨ TOP TIER',
    'prospect': 'PROSPECT',
    'secureBestTalent': 'Secure the world\'s best talent.',
    'budgetAvailable': 'Budget Available',
    'target': 'Target',
    'buyDirect': 'Buy Direct',
    'negotiate': 'Negotiate',
    'noPlayersFound': 'No {pos} players found.',
    'marketClosed': 'Market Closed.',
    'transferNegotiation': 'Transfer Negotiation',
    'currentClub': 'Current Club',
    'marketValue': 'Market Value',
    'yourBudget': 'Your Budget',
    'roundSlash': 'Round',
    'counter': 'Counter',
    'weAreListening': 'We are listening to offers.',
    'cannotAffordOffer': 'You cannot afford this offer.',
    'fairPriceAccepted': 'That is a fair price. We accept.',
    'tooFarApart': 'We are too far apart. Negotiations are over.',
    'thatIsInsulting': 'That is insulting. We want',
    'valueHigher': 'We value him much higher. Pay',
    'andHeIsYours': 'and he is yours.',
    'weAreClose': 'We are close, but we need',
    'cannotAffordCounter': 'You cannot afford our counter offer!',
    'offerAccepted': 'Offer Accepted!',
    'playerJoiningSquad': 'The player is joining your squad for',
    'lookingForSalary': 'I am looking for a salary that reflects my ability.',
    'happyWithTerms': 'I\'m happy with these terms. Where do I sign?',
    'cannotReachAgreement': 'I don\'t think we can reach an agreement. Talks are over.',
    'notEvenClose': 'That\'s not even close. For a',
    'yearDeal': '-year deal, I need at least',
    'higherClauseRequiresWage': '(Higher release clause requires higher wage)',
    'needToDoBetter': 'You\'ll need to do better than that.',
    'ambitiousAcceptance': 'I\'m excited to join a team with ambition like yours. Let\'s win trophies together!',
    'greedyAcceptance': 'The money is right. I\'m ready to sign.',
    'greedyRejection': 'I\'m not getting what I\'m worth. This isn\'t going to work.',
    'ambitiousRejection': 'I need to be at a club that matches my ambitions. Good luck.',
    'greedyLowOffer': 'That\'s way too low! I know my worth. I need at least {amount} for a {years}-year deal.',
    'ambitiousLowOffer': 'I want to be part of something special, but I still need fair compensation. At least {amount} for {years} years.',
    'greedyCloseOffer': 'You\'re getting closer, but I need more money.',
    'ambitiousCloseOffer': 'I like the direction, but the numbers need to work for both of us.',
    'youthFairOffer': 'That sounds fair. I\'m ready to sign.',
    'youthRejection': 'I don\'t feel valued here. I\'m going elsewhere.',
    'youthInsultingOffer': 'That\'s insulting! For a {years}-year deal I need at least {amount}.',
    'youthInitialMessage': 'I\'m looking for a standard contract to start my career.',
    'youthNegotiationFailed': 'Could not reach an agreement with {name}. The player has left the academy.',
    'role': 'Role',
    'contractLength': 'Contract Length',
    'futureProspect': 'Future Prospect',
    'transferHistory': 'Transfer History',
    'noTransfersYet': 'No transfers yet',
    'managerOffers': 'Manager Job Offers',
    'manager': 'Manager',
    'newOpportunities': 'New Opportunities',
    'offersReceived': 'You\'ve received {count} job offer(s) from other clubs',
    'currentTeam': 'Current Team',
    'teamRating': 'Team Rating',
    'elitePrestige': 'ELITE',
    'highPrestige': 'HIGH',
    'mediumPrestige': 'MEDIUM',
    'lowPrestige': 'LOW',
    'waitingForManagerOffers': 'Review manager offers below',
    'offerReasonChampionshipWinner': 'Championship Winner - {teamName} won the league!',
    'offerReasonTop3Finish': 'Top 3 Finish - Your team finished {rank}',
    'offerReasonTop6Finish': 'Top 6 Finish - Strong season performance',
    'offerReasonChampionshipImpressive': 'Championship Winner - Impressive achievement!',
    'offerReasonSolidSeason': 'Solid Season - Finished {rank}th',
    'offerReasonGoodPerformance': 'Good Performance',
    'offerReasonNewOpportunity': 'New Opportunity',
    'offerReasonLookingForLeadership': 'Looking for New Leadership',
    'offerReasonRebuilding': 'Rebuilding Opportunity',
    'seasonComplete': 'Season Complete',
    'finalRank': 'Final Rank',
    'champion': 'Champion',
    'wonPrize': 'Won {amount} prize',
    'prizeMoney': 'Prize Money',
    'seasonPlayer': 'Season Player',
    'goalsConceded': 'goals conceded',
    'longestUnbeatenStreak': 'Longest Unbeaten Streak',
    'longestWinStreak': 'Longest Win Streak',
    'matchesRecord': '{matches} matches - {team}\'s record',
    'viewDevelopmentReport': 'VIEW DEVELOPMENT REPORT',
    'mvpCount': 'MVP Count',
    'avgRating': 'Avg Rating',
    'passes': 'Passes',
    'passAccuracy': 'Pass Accuracy',
    'pace': 'Pace',
    'shooting': 'Shooting',
    'passing': 'Passing',
    'dribbling': 'Dribbling',
    'defending': 'Defending',
    'physical': 'Physical',
    'showStats': 'Show Stats',
    'showBasicInfo': 'Show Basic Info',
    'awards': 'Awards',
    'topScorer': 'Top Scorer',
    'achievements': 'Achievements',
    'myAchievements': 'My Career Achievements',
    'totalAchievements': 'Total Achievements',
    'seasons': 'Seasons',
    'achievementWon': 'won',
    'noAchievementsYet': 'No achievements yet',
    'startPlayingToEarnAchievements': 'Start playing to earn achievements!',
    'championship': 'Championship',
    'championships': 'Championships',
    'runnerUp': 'Runner Up',
    'thirdPlace': 'Third Place',
    'topFour': 'Top Four',
    'relegationAvoided': 'Relegation Avoided',
    'mvpPlayer': 'MVP Player',
    'topScorerPlayer': 'Top Scorer Player',
    'topAssisterPlayer': 'Top Assister Player',
    'seasonGoalkeeperPlayer': 'Season Goalkeeper Player',
    'unbeatenStreak': 'Unbeaten Streak',
    'winStreak': 'Win Streak',
    'financialSuccess': 'Financial Success',
    'endOfSeason': 'End of Season',
    'developmentReport': 'DEVELOPMENT REPORT',
    'tapPlayerToSeeEvolution': 'Tap a player to see their attribute evolution.',
    'tapToClose': 'Tap to close',
    'improvers': 'Improvers',
    'declining': 'Declining',
    'playersMaintainedRating': 'players maintained their rating',
    'squadNetChange': 'Squad Net Change',
    'developmentBreakthrough': 'Development Breakthrough!',
    'developmentBreakthroughDescription': '{name} has improved significantly in key areas. Their value has increased.',
    'regression': 'Regression',
    'regressionDescription': '{name} is showing signs of decline. Physical attributes are dropping.',
    'startNextSeason': 'START NEXT SEASON',
    'expiringContracts': 'Expiring Contracts',
    'expiringContractsDescription': 'You must renew or release all players with expiring contracts before starting the new season.',
    'allContractsHandled': 'All contracts handled!',
    'continueToNewSeason': 'Continue to New Season',
    'expiringContractsCount': '{count} player(s) with expiring contracts',
    'currentWage': 'Current Wage',
    'renewContract': 'Renew Contract',
    'release': 'Release',
    'cannotProceedUntilContractsHandled': 'You cannot proceed to the new season until all expiring contracts are handled.',
    'noStatChanges': 'No specific attribute changes recorded.',
    'stadiumExpansion': 'Stadium Expansion',
    'careerTimeline': 'Career Timeline',
    'leaguePosition': 'League Position',
    'free': 'Free',
    'youth': 'Youth',
    'allPlayers': 'All Players',
    'team': 'Team',
    'approachPlayer': 'Approach Player',
    'pendingOffers': 'Pending Offers',
    'playerSold': 'Player sold, will leave the team in the next transfer window.',
    'transferFee': 'Transfer Fee',
    'loanFee': 'Loan Fee',
    'wageOffer': 'Wage Offer',
    'clickToRespond': 'Click to respond',
    'transfer': 'Transfer',
    'loan': 'Loan',
    'listPlayerTitle': 'List Player',
    'listPlayerDescription': 'Choose how to list {playerName}:',
    'addToLoanList': 'Add to Loan List',
    'addToTransferList': 'Add to Transfer List',
    'releasePlayer': 'Release Player',
    'from': 'From',
    'to': 'To',
    'type': 'Type',
    'date': 'Date',
    'contractRenewal': 'Contract Renewal',
    'playerReaction': 'Player Reaction',
    'contractDuration': 'Contract Duration',
    'shortTerm': 'Short term (Higher Wage)',
    'longTerm': 'Long term (Lower Wage)',
    'standard': 'Standard',
    'weeklyWageOffer': 'Weekly Wage Offer',
    'includeReleaseClause': 'Include Release Clause',
    'playerWants': 'Player wants',
    'submitOffer': 'SUBMIT OFFER',
    'confirmSignature': 'CONFIRM SIGNATURE',
    'termsAgreed': 'Terms Agreed!',
    'walkedAway': 'Walked Away',
    'agreedTo': 'Agreed to',
    'for': 'for',
    'years': 'years',
    'negotiationsBrokenDown': 'Negotiations have broken down.',
    'squadDetailsUnavailable': 'Squad details unavailable in preview.',
    'weeklyWageBill': 'Weekly Wage Bill',
    'financialReport': 'Financial Report',
    'seasonTotal': 'Season Total',
    'income': 'Income',
    'expenses': 'Expenses',
    'matchTickets': 'Match Tickets',
    'sponsors': 'Sponsors',
    'transfersIn': 'Transfers In',
    'playerWages': 'Player Wages',
    'transfersOut': 'Transfers Out',
    'operations': 'Operations',
    'estimatedBasedOnContracts': 'Estimated based on current contracts',
    'roster': 'ROSTER',
    'backToLeague': 'Back to League',
    'age': 'Age',
    'rating': 'Rating',
    'potential': 'Potential',
    'value': 'Value',
    'traits': 'Traits',
    'netProfitLoss': 'Net Profit/Loss',
    'renew': 'Renew',
    'sell': 'Sell',
    'fanStadiumInfo': 'Fan & Stadium Info',
    'fanCount': 'Fan Count',
    'stadiumCapacity': 'Stadium Capacity',
    'fanMorale': 'Fan Morale',
    'clubReputation': 'Club Reputation',
    'currentPrices': 'Current Prices',
    'ticketPrice': 'Ticket Price',
    'baseTicketPrice': 'Base Ticket Price',
    'shirtPrice': 'Shirt Price',
    'priceManagement': 'Price Management',
    'base': 'Base',
    'capacity': 'Capacity',
    'fans': 'Fans',
    'expansionInProgress': 'Expansion in Progress',
    'newCapacity': 'New Capacity',
    'completion': 'Completion',
    'weeksRemaining': 'Weeks Remaining',
    // Stadium Sponsorship
    'stadiumSponsorOffer': 'Stadium Naming Rights Offer',
    'sponsorOfferDescription': 'is interested in sponsoring your stadium.',
    'sponsorCompany': 'Sponsor Company',
    'proposedStadiumName': 'Proposed Stadium Name',
    'financialTerms': 'Financial Terms',
    'annualPayment': 'Annual Payment',
    'totalContractValue': 'Total Contract Value',
    'currentSponsor': 'Current Stadium Sponsor',
    'replacingSponsor': 'Accepting this offer will replace your current sponsor.',
    'offerExpiresIn': 'This offer expires in',
    'offerExpired': 'This offer has expired.',
    'acceptOffer': 'Accept Offer',
    'acceptAndTerminate': 'Accept & Pay',
    'insufficientBudget': 'Insufficient Budget',
    'clickToView': 'Click to view',
    'reject': 'Reject Offer',
    'rejectAllOffers': 'Reject All Offers',
    'contractActive': 'Contract is still active.',
    'contractExpired': 'Contract has expired. You can accept a new sponsor without penalty.',
    'contractEndsIn': 'Contract ends in',
    'expired': 'Expired',
    'terminationFee': 'Termination Fee Required',
    'terminationFeeDescription': 'You must pay the remaining contract value to terminate early.',
    'year': 'year',
    // Sponsorships
    'sponsorships': 'Sponsorships',
    'sponsorshipsDescription': 'Manage your sponsorship deals and explore new opportunities',
    'sponsorshipsMenuDescription': 'Manage sponsorship deals',
    'viewSponsorships': 'View Sponsorships',
    'activeSponsorships': 'Active Sponsorships',
    'active': 'Active',
    'selectSponsor': 'Select Sponsor',
    'alreadyActive': 'Already Active',
    'estimatedValue': 'Estimated Value',
    'generateNew': 'New Offer',
    'selectOffer': 'Select Offer',
    'available': 'available',
    'offers': 'offers',
    'availableOffers': 'Available Offers',
    'allOffersRejectedMessage': 'Unfortunately, there are no offers available at the moment. New offers may arrive in the future.',
    'level': 'Level',
    'tier1': 'Ulusal & Mid-Tier',
    'tier2': 'Ulusal + Yarı-Global',
    'tier3': 'Global',
    'tier4': 'Prestige Tier',
    'sponsorOffer': 'Sponsor Offer',
    // Sponsorship Categories
    'jersey': 'Jersey',
    'matchday': 'Matchday',
    'digital': 'Digital',
    'stadiumSponsorships': 'Stadium sponsorships',
    'jerseySponsorships': 'Jersey sponsorships',
    'matchdaySponsorships': 'Matchday sponsorships',
    'digitalSponsorships': 'Digital sponsorships',
    'totalSponsorIncome': 'Total Sponsor Income',
    'selectSponsorshipType': 'Select a sponsorship type to view offers',
    'contractEnds': 'Contract ends',
    'viewContract': 'View Contract',
    'selectOneOffer': 'Select one of the following offers',
    // Sponsorship Types
    'namingRights': 'Naming Rights',
    'vipSkybox': 'VIP Skybox',
    'ledBoards': 'LED Boards',
    'stadiumTech': 'Stadium Tech',
    'jerseyFront': 'Jersey Front',
    'jerseyBack': 'Jersey Back',
    'jerseySleeve': 'Jersey Sleeve',
    'trainingKit': 'Training Kit',
    'matchdayPresentation': 'Matchday Presentation',
    'officialDrink': 'Official Drink',
    'officialMerchandise': 'Official Merchandise',
    'matchdayBroadcast': 'Matchday Broadcast',
    'socialMedia': 'Social Media',
    'appPartnership': 'App Partnership',
    'esports': 'Esports',
    'streamingPlatform': 'Streaming Platform',
    // Tier Names
    'tierLocalRegional': 'Local/Regional',
    'tierNational': 'National',
    'tierMajorNational': 'Major National/International',
    'tierInternational': 'International',
    'tierPremiumInternational': 'Premium International',
    'tierWorldClass': 'World-Class',
    'tier': 'Tier',
    // Squad View
    'availableFunds': 'Available Funds',
    'stadiumCapacityLimitReached': 'Stadium capacity limit reached. From now on, growth means prestige — not size.',
    'unableToExpandStadium': 'Unable to expand stadium.',
    // Negotiation Modal
    'negotiationsFailed': 'Negotiations Failed',
    'clubPulledOutOfTalks': 'The club has pulled out of talks.',
    'walkAway': 'Walk Away',
    'accept': 'Accept',
    'completeTransfer': 'Complete Transfer',
    'season': 'Season',
    'standings': 'Standings',
    'latestResults': 'Latest Results',
    'leagueStats': 'League Stats',
    'fixtures': 'Fixtures',
    'seasonSummary': 'SEASON SUMMARY',
    'played': 'P',
    'won': 'W',
    'drawn': 'D',
    'lost': 'L',
    'goalsFor': 'GF',
    'goalsAgainst': 'GA',
    'goalDifference': 'GD',
    'current': 'Current',
    'currentWeek': 'Current Week',
    'transferWindow': 'Transfer Window',
    'transferWindowNoMatches': 'Transfer Window - No matches scheduled',
    'you': 'You',
    'next': 'Next',
    'inspect': 'Inspect',
    'topScorers': 'Top Scorers',
    'topAssists': 'Top Assists',
    'discipline': 'Discipline',
    'winStreaks': 'Win Streaks',
    'unbeatenStreaks': 'Unbeaten Streaks',
    'squadValue': 'Squad Value',
    'wins': 'Wins',
    'unbeaten': 'Unbeaten',
    'noCardsYet': 'No cards yet',
    // Months
    'month.jan': 'Jan',
    'month.feb': 'Feb',
    'month.mar': 'Mar',
    'month.apr': 'Apr',
    'month.may': 'May',
    'month.jun': 'Jun',
    'month.jul': 'Jul',
    'month.aug': 'Aug',
    'month.sep': 'Sep',
    'month.oct': 'Oct',
    'month.nov': 'Nov',
    'month.dec': 'Dec',
    // Retirement
    'retirementWarning': 'Retirement Considerations',
    'retirementWarningDescription': 'Some players are considering retirement at the end of the season.',
    'retirementMessage': '{name} is considering retiring at the end of the season.',
    'persuadeToContinue': 'Persuade to Continue',
    'respectDecision': 'Respect Decision',
    'processing': 'Processing...',
    'retirementAnnounced': 'Retirement Announced',
    'playerRetiring': 'Player Retiring',
    'injured': 'Injured',
    'ill': 'Ill',
    'suspended': 'Suspended',
    'weekOut': 'week out',
    'weeksOut': 'weeks out',
    'game': 'game',
    'games': 'games',
    'contractStatus': 'Contract Status',
    'weeklyWage': 'Weekly Wage',
    'duration': 'Duration',
    'releaseClause': 'Release Clause',
    'none': 'None',
    'pendingTransfer': 'Pending Transfer',
    'willJoinInWeek': 'Will join',
    'inWeek': 'in Week',
    'fee': 'Fee',
    'seasonStatistics': 'Season Statistics',
    'cards': 'Cards',
    'currentAbility': 'Current Ability',
    'matchPerformanceHistory': 'Match Performance History',
    'opponent': 'Opponent',
    'result': 'Result',
    'passPercent': 'Pass%',
    'saves': 'Saves',
    'tackles': 'Tkl',
    'interceptions': 'Int',
    'minutes': 'Min',
    'showingLastMatches': 'Showing last',
    'ofMatches': 'of',
    'matchesLower': 'matches',
    'debtWarning': 'Financial Warning',
    'debtWarningMessage': 'The club president has issued a warning. Your club finished the season in debt.',
    'debtClearedMessage': 'The president has cleared your debts this time, but this cannot happen again. Manage your finances better next season!',
    'understood': 'Understood',
    'gameOver': 'GAME OVER',
    'gameOverMessage': 'The club president has fired you. Your club finished the season in debt for the second time.',
    'gameOverDescription': 'Poor financial management has cost you your job. Better luck next time!',
    'backToCareerSelect': 'Back to Career Select',
    'hasRecoveredFrom': 'has recovered from',
    'hasSuffered': 'has suffered a',
    'hasContracted': 'has contracted',
    'outFor': 'Out for',
    'viewPerformances': 'View Performances',
    // Injury Types
    'injury.hamstringstrain': 'Hamstring Strain',
    'injury.kneeligamentsprain': 'Knee Ligament Sprain',
    'injury.anklesprain': 'Ankle Sprain',
    'injury.groinstrain': 'Groin Strain',
    'injury.calfstrain': 'Calf Strain',
    'injury.shoulderdislocation': 'Shoulder Dislocation',
    'injury.fracturedrib': 'Fractured Rib',
    'injury.acltear': 'ACL Tear',
    'injury.mclinjury': 'MCL Injury',
    'injury.achillestendonitis': 'Achilles Tendonitis',
    'injury.concussion': 'Concussion',
    'injury.backstrain': 'Back Strain',
    'injury.hipflexorstrain': 'Hip Flexor Strain',
    'injury.meniscustear': 'Meniscus Tear',
    'injury.fracturedmetatarsal': 'Fractured Metatarsal',
    // Illness Types
    'illness.flu': 'Flu',
    'illness.foodpoisoning': 'Food Poisoning',
    'illness.viralinfection': 'Viral Infection',
    'illness.stomachbug': 'Stomach Bug',
    'illness.respiratoryinfection': 'Respiratory Infection',
    'illness.fever': 'Fever',
    'illness.bronchitis': 'Bronchitis',
    'illness.pneumonia': 'Pneumonia',
    'illness.mononucleosis': 'Mononucleosis',
    'illness.migraine': 'Migraine',
  },
  tr: {
    // Language Selection
    'selectLanguage': 'Dil Seçin',
    'english': 'İngilizce',
    'turkish': 'Türkçe',
    'continue': 'Devam Et',
    
    // Career Selection
    'selectCareerSlot': 'Kayıt Yeri Seçin',
      'chooseSlot': 'Kariyerinize başlamak veya devam etmek için bir kayıt yeri seçin',
      'slot': 'Kayıt', // veya 'Slot'
      'empty': 'Boş',
      'lastPlayed': 'Son Oynama',
      'deleteCareer': 'Kariyeri Sil?',
      'deleteCareerConfirm': 'Bu kariyer kalıcı olarak silinecek. Devam etmek istediğinize emin misiniz?',
      'cancel': 'İptal',
      'delete': 'Sil',
  
      // Main Menu
      'mainMenu': 'ANA MENÜ',
      'welcome': 'Hoş Geldiniz',
      'teamManagement': 'TAKIM YÖNETİMİ',
      'squad': 'Kadro',
      'rosterView': 'Kadro Görünümü',
      'viewAndManage': 'Kadronuzu görüntüleyin ve yönetin',
      'formationView': 'Diziliş Görünümü', // Formasyon yerine Diziliş daha yaygın
      'startingXI': 'İlk 11 ve Taktikler',
      'financialTable': 'Mali Durum',
      'incomeExpenses': 'Gelir, gider ve bütçe',
      'clubManagement': 'Kulüp Yönetimi',
      'club': 'Kulüp',
      'favorites': 'Favoriler',
      'favoritesTitle': 'FAVORİLER',
      'trackPlayersDescription': 'Ligdeki favori oyuncularınızı takip edin.',
      'totalFavorites': 'Toplam Favori',
      'noFavoritePlayersYet': 'Henüz favori oyuncu yok. Transfer Pazarından veya diğer takımlardan oyuncu ekleyin.',
      'remove': 'Kaldır',
      'freeAgent': 'Serbest Oyuncu',
      'trackPlayers': 'Favori oyuncularınızı takip edin',
      'transfers': 'Transferler',
      'transferMarket': 'Transfer Pazarı',
      'browsePlayers': 'Mevcut oyunculara göz atın',
      'leagueHub': 'LİG MERKEZİ',
      'leagueHubCard': 'Lig Merkezi',
      'standingsResults': 'Puan Durumu, Sonuçlar, İstatistikler ve Fikstür',
      'transferOfferTitle': 'Transfer Teklifi',
      'loanOfferTitle': 'Kiralama Teklifi',
      'expires': 'Sona Erme',
      'negotiationRound': 'Görüşme Turu',
      'waitingForResponse': 'Yanıt bekleniyor...',
      'counterReviewNextWeek': 'Karşı teklifiniz gelecek hafta değerlendirilecek.',
      'later': 'Daha Sonra',
      'offerHistory': 'Teklif Geçmişi',
      'initialOffer': 'İlk Teklif',
      'roundLabel': '{round}. Tur',
      'historyNoteInitial': 'İlk teklif',
      'historyNoteCounter': 'Karşı teklif',
      'historyNoteAccepted': 'Karşı teklif kabul edildi',
      'historyNoteRejected': 'Teklif reddedildi',
      'counterOfferTitle': 'Karşı Teklif',
      'currentOffer': 'Güncel Teklif',
      'makeCounterOffer': 'Karşı Teklif Yap',
      'rotateDevice': 'Cihazınızı Çevirin',
      'rotateDeviceMessage': 'Lütfen oyunu oynamak için cihazınızı yatay moda çevirin.',
      'rotateDeviceSubmessage': 'Oyun yatay ekran yönlendirmesi gerektirir.',
      'minLabel': 'Min',
      'originalLabel': 'Orijinal',
      'maxLabel': 'Maks',
      'sendCounterOffer': 'Karşı Teklif Gönder',
      'responseNextWeek': 'Yanıt gelecek hafta verilecek',
      'mailboxTitle': 'Posta Kutusu',
      'mailboxMenuDescription': 'Tüm bildirimler ve haberler',
      'mailboxEmptyTitle': 'Posta kutusu boş',
      'mailboxEmptyDescription': 'Önemli bildirimler, transfer sonuçları ve pazarlıklar burada listelenir.',
      'markAllRead': 'Tümünü okundu say',
      'clearAll': 'Hepsini sil',
      'markRead': 'Okundu işaretle',
      'markUnread': 'Okunmadı işaretle',
      'unread': 'okunmamış',
      'noMessages': 'Henüz mesaj yok',
  
      // Common
      'exitToCareerSelect': 'Kariyer Seçimine Dön',
      'save': 'Kaydet',
      'gameSaved': 'Oyun başarıyla kaydedildi!',
      'noSaveData': 'Bu alanda kayıtlı veri bulunamadı.',
      'loadError': 'Kariyer yüklenemedi. Lütfen tekrar deneyin.',
      // Shop
      'shop': 'Mağaza',
      'shopDescription': 'Takımınız için güçlendirmeler ve geliştirmeler alın',
      'shopMenuDescription': 'Güçlendirmeler ve geliştirmeler',
      'shopItems': 'Mağaza Ürünleri',
      'legendaryPlayers': 'Efsane Futbolcular',
      'legendaryPack': 'Efsane Paket',
      'legendaryPackDesc': 'Efsane bir futbolcu (90+ Reyting) kazanma şansı',
      'premiumPack': 'Premium Paket',
      'elitePack': 'Elit Paket',
      'standardPack': 'Standart Paket',
      'selectPack': 'Paket Seç',
      'premiumTickets': 'Premium Biletler',
      'ticket': 'Bilet',
      'ticketUsed': 'Premium bilet kullanıldı!',
      'noPremiumTickets': 'Premium bilet yok! Kupa kazanarak bilet edinebilirsiniz.',
      'winTrophiesToEarnTickets': 'Kupa kazanarak bilet topla',
      'dropRates': 'Çıkma Oranları',
      'legendary': 'EFSANE',
      'epic': 'EPİK',
      'rare': 'NADİR',
      'common': 'SIRADAN',
      'drawing': 'Seçiliyor...',
      'drawPlayer': 'Oyuncu Aç',
      'openingPack': 'Paket Açılıyor...',
      'close': 'Kapat',
      'addToTeam': 'Takıma Ekle',
      'drawAgain': 'Tekrar Aç',
      'addedToTeam': 'takıma eklendi',
      'squadSizeLimitReached': 'Kadro limiti doldu! Önce oyuncu satmalısınız.',
      'tapToOpen': 'AÇMAK İÇİN DOKUN',
      'charging': 'YÜKLENİYOR...',
      'clickToPurchase': 'Satın Almak İçin Tıklayın',
      // Player Stats
      'pac': 'HIZ',
      'sho': 'ŞUT',
      'pas': 'PAS',
      'dri': 'DRİPLİNG', // "Driblling" düzeltildi
      'def': 'DEFANS',
      'phy': 'FİZİK',
      // Goalkeeper Stats
      'div': 'UÇMA', // Diving -> İndirme yerine Uçma/Uzanma daha doğru
      'han': 'YAKALAMA', // Handling -> Tutma/Yakalama
      'kic': 'DEGAJ', // Kicking -> Kaleci için Degaj veya Ayak kullanılır
      'ref': 'REFLEKS',
      'spd': 'HIZ',
      'gkPos': 'POZİSYON ALMA', // Goalkeeper Positioning -> Pozisyon Alma
      'boosts': 'Güçlendirmeler',
      'upgrades': 'Yükseltmeler',
      'special': 'Özel',
      'boost': 'Güçlendirme',
      'upgrade': 'Yükseltme',
      'price': 'Fiyat',
      'buy': 'Satın Al',
      'purchaseSuccess': 'Satın alma başarılı!',
      'insufficientFunds': 'Yetersiz bütçe!',
      'trainingBoost': 'Antrenman Desteği',
      'trainingBoostDesc': '1 ay boyunca oyuncu gelişim hızını %20 artırır',
      'scoutBoost': 'Gözlemci Desteği', // Scout -> Gözlemci
      'scoutBoostDesc': 'Sonraki 3 görev için gözlem süresini %50 azaltır',
      'fitnessBoost': 'Kondisyon Desteği',
      'fitnessBoostDesc': '1 ay boyunca sakatlık riskini %30 azaltır',
      'facilityUpgrade': 'Tesis Yükseltmesi',
      'facilityUpgradeDesc': 'Antrenman tesislerini kalıcı olarak iyileştirir (+%5 Gelişim)',
      'medicalUpgrade': 'Sağlık Merkezi Yükseltmesi',
      'medicalUpgradeDesc': 'Sakatlık iyileşme süresini kalıcı olarak %25 kısaltır',
      'youthFacility': 'Altyapı Yükseltmesi',
      'youthFacilityDesc': 'Gençlik akademisi kalitesini artırır (+%10 Daha iyi adaylar)',
      'transferBoost': 'Transfer Görüşmesi Desteği',
      'transferBoostDesc': 'Pazarlık başarı oranını %15 artırır',
      'fanBoost': 'Taraftar Morali Desteği',
      'fanBoostDesc': 'Taraftar moralini anında 10 puan artırır',
      'week': 'Hafta',
      'simWeek': 'HAFTAYI SİMÜLE ET',
      'simSeason': 'SEZONU SİMÜLE ET',
      'takeControl': 'KONTROLÜ AL',
      'youthAcademy': 'Altyapı',
      'scoutYouthPlayers': 'Genç yetenekleri keşfet ve takıma kat',
      'futureStars': 'GELECEĞİN YILDIZLARI',
      'noScoutingMissionActive': 'Aktif Gözlemci Görevi Yok',
      'scoutMissionDescription': 'Gözlemcilerinizi yerel akademilere göndererek yeni yetenekler bulun.',
      'thisWillCost': 'Maliyet:',
      'startScoutingMission': 'GÖZLEMCİ GÖNDER',
      'reload': 'Yenile',
      'promote': 'A TAKIMA AL', // Promote -> Yükselt yerine A Takıma Al daha jargona uygun
      'noProspectsFound': 'Oyuncu bulunamadı.',
      'noMoreProspects': 'Bu grupta başka oyuncu kalmadı.',
      'reloadScouting': 'YENİDEN ARAT',
      'contractNegotiation': 'Sözleşme Görüşmesi',
      'demand': 'Talep',
      'reaction': 'Tepki',
      'shortTermHigherWage': 'Kısa Vadeli (Yüksek Maaş)',
      'longTermLowerWage': 'Uzun Vadeli (Düşük Maaş)',
      'dealAgreed': 'Anlaşma Sağlandı!',
      'negotiationFailed': 'Görüşme Başarısız',
      'signedFor': 'İmzalandı',
      'playerRejectedTerms': 'Oyuncu şartları reddetti.',
      'welcomeToTheClub': 'KULÜBE HOŞ GELDİN',
      'worldClass': '💎 DÜNYA KLASI',
      'elite': '🌟 ELİT',
      'topTier': '✨ ÜST SEVİYE',
      'prospect': 'GENÇ YETENEK',
      'secureBestTalent': 'Dünyanın en iyi yeteneklerini kadrona kat.',
      'budgetAvailable': 'Mevcut Bütçe',
      'target': 'Hedef',
      'buyDirect': 'Satın Al',
      'negotiate': 'Pazarlık Et',
      'noPlayersFound': '{pos} mevkisinde oyuncu bulunamadı.',
      'marketClosed': 'Pazar Kapalı.',
      'transferNegotiation': 'Transfer Görüşmesi',
      'currentClub': 'Mevcut Kulüp',
      'marketValue': 'Piyasa Değeri', // Büyük İ düzeltildi
      'yourBudget': 'Bütçeniz', // Büyük İ düzeltildi
      'roundSlash': 'Tur',
      'counter': 'Karşı Teklif',
      'weAreListening': 'Teklifleri dinliyoruz.',
      'cannotAffordOffer': 'Bu teklifi karşılayacak bütçeniz yok.',
      'fairPriceAccepted': 'Bu adil bir fiyat. Kabul ediyoruz.',
      'tooFarApart': 'Çok uzaktayız. Görüşmeler sona erdi.',
      'thatIsInsulting': 'Bu bir hakaret. Biz...',
      'valueHigher': 'Oyuncumuz çok daha değerli. Şu fiyatı ödeyin:',
      'andHeIsYours': 've o sizin olsun.',
      'weAreClose': 'Yakınız, ama...',
      'cannotAffordCounter': 'Karşı teklifi karşılayamazsınız!',
      'offerAccepted': 'Teklif Kabul Edildi!',
      'playerJoiningSquad': 'Oyuncu kadronuza katılıyor',
      'lookingForSalary': 'Yeteneklerimi yansıtan bir maaş istiyorum.',
      'happyWithTerms': 'Şartlardan memnunum. Nereye imza atıyoruz?',
      'cannotReachAgreement': 'Anlaşabileceğimizi sanmıyorum. Görüşme bitti.',
      'notEvenClose': 'Teklifiniz beklentimin çok altında.',
      'yearDeal': 'yıllık sözleşme için',
      'higherClauseRequiresWage': '(Yüksek serbest kalma bedeli, yüksek maaş gerektirir)',
      'needToDoBetter': 'Daha iyi bir teklif yapmalısınız.',
      'ambitiousAcceptance': 'Sizin gibi hırslı bir takıma katılmaktan heyecanlıyım. Birlikte kupa kazanalım!',
      'greedyAcceptance': 'Para uygun. İmzaya hazırım.',
      'greedyRejection': 'Değerimi alamıyorum. Bu iş olmayacak.',
      'ambitiousRejection': 'Hırslarıma uygun bir kulüpte olmam gerekiyor. İyi şanslar.',
      'greedyLowOffer': 'Bu çok düşük! Değerimi biliyorum. En az {amount} {years} yıllık sözleşme için gerekiyor.',
      'ambitiousLowOffer': 'Özel bir şeyin parçası olmak istiyorum, ama yine de adil bir ücret istiyorum. En az {amount} {years} yıl için.',
      'greedyCloseOffer': 'Yaklaşıyorsunuz, ama daha fazla para istiyorum.',
      'ambitiousCloseOffer': 'Yönü beğendim, ama sayılar ikimiz için de çalışmalı.',
      'youthFairOffer': 'Bu adil görünüyor. İmzaya hazırım.',
      'youthRejection': 'Burada değer görmediğimi hissediyorum. Başka yere gidiyorum.',
      'youthInsultingOffer': 'Bu hakaret edici! {years} yıllık sözleşme için en az {amount} gerekiyor.',
      'youthInitialMessage': 'Kariyerime başlamak için standart bir sözleşme arıyorum.',
      'youthNegotiationFailed': '{name} ile anlaşamadınız. Oyuncu altyapıdan ayrıldı.',
      'ovr': 'GEN', // OVR -> GEN (Genel) veya REY (Reyting) kullanılır
      'thrilled': 'ÇOK MEMNUN',
      'happy': 'MUTLU',
      'interested': 'İLGİLİ',
      'skeptical': 'ŞÜPHELİ',
      'annoyed': 'SİNİRLİ',
      'insulted': 'AŞAĞILANMIŞ',
      'waiting': 'BEKLİYOR...',
      'role': 'Rol',
      'contractLength': 'Sözleşme Süresi',
      'futureProspect': 'Gelecek Vaadeden',
      'transferHistory': 'Transfer Geçmişi',
      'noTransfersYet': 'Henüz transfer yok',
      'managerOffers': 'İş Teklifleri',
      'manager': 'Teknik Direktör',
      'newOpportunities': 'Yeni Fırsatlar',
      'offersReceived': 'Diğer kulüplerden {count} teklif aldınız',
      'currentTeam': 'Mevcut Takım',
      'teamRating': 'Takım Gücü',
      'elitePrestige': 'ELİT',
      'highPrestige': 'YÜKSEK',
      'mediumPrestige': 'ORTA',
      'lowPrestige': 'DÜŞÜK',
      'waitingForManagerOffers': 'Gelen teklifleri inceleyin',
      'offerReasonChampionshipWinner': 'Şampiyon - {teamName} ligi kazandı!',
      'offerReasonTop3Finish': 'İlk 3 - Takımınız {rank}. sırada bitirdi',
      'offerReasonTop6Finish': 'İlk 6 - Güçlü sezon performansı',
      'offerReasonChampionshipImpressive': 'Şampiyon - Etkileyici başarı!',
      'offerReasonSolidSeason': 'Sağlam Sezon - {rank}. sırada bitirdi',
      'offerReasonGoodPerformance': 'İyi Performans',
      'offerReasonNewOpportunity': 'Yeni Fırsat',
      'offerReasonLookingForLeadership': 'Yeni Liderlik Arıyor',
      'offerReasonRebuilding': 'Yeniden Yapılanma Fırsatı',
      'seasonComplete': 'Sezon Tamamlandı',
      'finalRank': 'Sezon Sonu Sıralaması',
      'champion': 'Şampiyon',
      'wonPrize': '{amount} ödül kazanıldı',
      'prizeMoney': 'Para Ödülü',
      'seasonPlayer': 'Sezonun Oyuncusu',
      'goalsConceded': 'yenen gol',
      'longestUnbeatenStreak': 'En Uzun Yenilmezlik',
      'longestWinStreak': 'En Uzun Galibiyet Serisi',
      'matchesRecord': '{matches} maç - {team} rekoru',
      'viewDevelopmentReport': 'GELİŞİM RAPORUNU GÖRÜNTÜLE',
      'with': 'ile',
      'mvpCount': 'Maçın Adamı', // MVP yerine Maçın Adamı
      'avgRating': 'Ort. Puan',
      'passes': 'Pas',
      'passAccuracy': 'Pas İsabeti',
      'pace': 'Hız',
      'shooting': 'Şut',
      'passing': 'Pas',
      'dribbling': 'Dribling',
      'defending': 'Savunma',
      'physical': 'Fizik',
      'showStats': 'İstatistikleri Göster',
      'showBasicInfo': 'Temel Bilgileri Göster',
      'awards': 'Ödüller',
      'topScorer': 'Gol Kralı',
      'achievements': 'Başarılar',
      'myAchievements': 'Kariyer Başarılarım',
      'totalAchievements': 'Toplam Başarı',
      'seasons': 'Sezon',
      'achievementWon': 'kazanıldı',
      'noAchievementsYet': 'Henüz başarı kazanılmadı',
      'startPlayingToEarnAchievements': 'Başarı kazanmak için oynamaya başlayın!',
      'championship': 'Şampiyonluk',
      'championships': 'Şampiyonluklar',
      'runnerUp': 'İkincilik',
      'thirdPlace': 'Üçüncülük',
      'topFour': 'İlk Dört',
      'relegationAvoided': 'Kümede Kalma',
      'mvpPlayer': 'Sezonun Yıldızı',
      'topScorerPlayer': 'Gol Kralı',
      'topAssisterPlayer': 'Asist Kralı',
      'seasonGoalkeeperPlayer': 'Sezonun Kalecisi',
      'unbeatenStreak': 'Yenilmezlik Serisi',
      'winStreak': 'Galibiyet Serisi',
      'financialSuccess': 'Finansal Başarı',
      'endOfSeason': 'Sezon Sonu',
      'developmentReport': 'GELİŞİM RAPORU',
      'tapPlayerToSeeEvolution': 'Gelişimini görmek için bir oyuncuya dokunun.',
      'tapToClose': 'Kapatmak için dokunun',
      'improvers': 'Gelişenler',
      'declining': 'Gerileyenler',
      'playersMaintainedRating': 'oyuncu gücünü korudu',
      'squadNetChange': 'Kadro Net Değişim',
      'developmentBreakthrough': 'Gelişim Patlaması!',
      'developmentBreakthroughDescription': '{name} kendini aştı ve özelliklerini ciddi oranda geliştirdi.',
      'regression': 'Gerileme',
      'regressionDescription': '{name} yaşlanma belirtileri gösteriyor. Fiziksel özellikleri düşüşte.',
      'startNextSeason': 'YENİ SEZONA BAŞLA',
      'expiringContracts': 'Biten Sözleşmeler',
      'expiringContractsDescription': 'Yeni sezona başlamadan önce sözleşmesi biten oyuncularla ilgilenmelisiniz.',
      'allContractsHandled': 'Tüm sözleşmeler tamam!',
      'continueToNewSeason': 'Yeni Sezona Geç',
      'expiringContractsCount': '{count} oyuncunun sözleşmesi bitiyor',
      'currentWage': 'Mevcut Maaş',
      'renewContract': 'Sözleşme Yenile',
      'release': 'Serbest Bırak',
      'cannotProceedUntilContractsHandled': 'Tüm sözleşme sorunları çözülmeden yeni sezona geçemezsiniz.',
      'noStatChanges': 'Özellik değişikliği yok.',
      'stadiumExpansion': 'Stadyum Genişletme',
      'careerTimeline': 'Kariyer Zaman Çizelgesi',
      'leaguePosition': 'Lig Pozisyonu',
      'free': 'Bedelsiz',
      'youth': 'Altyapı',
      'from': 'Gelen',
      'to': 'Giden',
      'type': 'Tür',
      'date': 'Tarih',
      'allPlayers': 'Tüm Oyuncular',
      'team': 'Takım',
      'approachPlayer': 'İletişime Geç',
      'pendingOffers': 'Bekleyen Teklifler',
      'playerSold': 'Oyuncu satıldı, bir sonraki transfer sezonunda takımdan ayrılacak.',
      'transferFee': 'Bonservis Bedeli',
      'loanFee': 'Kiralama Bedeli',
      'wageOffer': 'Maaş Teklifi',
      'clickToRespond': 'Yanıtlamak için tıkla',
      'transfer': 'Transfer',
      'loan': 'Kiralama',
      'listPlayerTitle': 'Transfer Listesi',
      'listPlayerDescription': '{playerName} için transfer durumu belirleyin:',
      'addToLoanList': 'Kiralık Listesine Ekle',
      'addToTransferList': 'Satılık Listesine Ekle',
      'releasePlayer': 'Oyuncuyu Serbest Bırak',
      'contractRenewal': 'Sözleşme Yenileme',
      'round': 'Tur',
      'playerReaction': 'Oyuncu Tepkisi',
      'contractDuration': 'Sözleşme Süresi',
      'shortTerm': 'Kısa Vadeli',
      'longTerm': 'Uzun Vadeli',
      'standard': 'Standart',
      'weeklyWageOffer': 'Haftalık Maaş Teklifi',
      'includeReleaseClause': 'Serbest Kalma Bedeli Ekle',
      'playerWants': 'Oyuncu isteği',
      'submitOffer': 'TEKLİF GÖNDER',
      'confirmSignature': 'İMZAYI ONAYLA',
      'termsAgreed': 'Şartlar Kabul Edildi!',
      'walkedAway': 'Masadan Kalktı',
      'agreedTo': 'Kabul etti',
      'for': 'bedeli:',
      'years': 'yıl',
      'negotiationsBrokenDown': 'Görüşmeler tıkandı.',
      'squadDetailsUnavailable': 'Kadro detayları önizlemede mevcut değil.',
      'weeklyWageBill': 'Haftalık Maaş Bütçesi',
      'financialReport': 'MALİ RAPOR',
      'seasonTotal': 'Sezon Toplamı',
      'income': 'Gelir',
      'expenses': 'Gider',
      'matchTickets': 'Maç Biletleri',
      'sponsors': 'Sponsorlar',
      'transfersIn': 'Gelen Transferler',
      'playerWages': 'Oyuncu Maaşları',
      'transfersOut': 'Giden Transferler',
      'operations': 'Operasyonel Giderler',
      'estimatedBasedOnContracts': 'Mevcut sözleşmelere dayalı tahmin',
      'roster': 'KADRO',
      'backToLeague': 'Lige Dön',
      'player': 'Oyuncu',
      'pos': 'MEVKİ',
      'age': 'Yaş',
      'rating': 'Güç', // Rating -> Güç veya Reyting
      'potential': 'POTANSİYEL',
      'value': 'DEĞER', // Value -> Değer
      'wage': 'Maaş',
      'traits': 'ÖZELLİKLER',
      'action': 'İşlem',
      'netProfitLoss': 'Net Kâr/Zarar',
      'renew': 'Yenile',
      'sell': 'Sat',
      'fanStadiumInfo': 'TARAFTAR VE STADYUM',
      'fanCount': 'Taraftar Sayısı',
      'stadiumCapacity': 'Stadyum Kapasitesi',
      'fanMorale': 'Taraftar Morali',
      'clubReputation': 'Kulüp İtibarı',
      'currentPrices': 'GÜNCEL FİYATLAR',
      'ticketPrice': 'Bilet Fiyatı',
      'baseTicketPrice': 'Taban Bilet Fiyatı',
      'shirtPrice': 'Forma Fiyatı',
      'priceManagement': 'FİYAT YÖNETİMİ',
      'base': 'Taban',
      'capacity': 'Kapasite',
      'fans': 'Taraftar',
      'expansionInProgress': 'Genişletme Sürüyor',
      'newCapacity': 'Yeni Kapasite',
      'completion': 'Tamamlanma',
      'weeksRemaining': 'Kalan Hafta',
      // Stadium Sponsorship
      'stadiumSponsorOffer': 'Stadyum İsim Sponsorluğu',
      'sponsorOfferDescription': 'stadyumunuza isim sponsoru olmak istiyor.',
      'sponsorCompany': 'Sponsor Firma',
      'proposedStadiumName': 'Önerilen Stadyum Adı',
      'financialTerms': 'Mali Şartlar',
      'annualPayment': 'Yıllık Ödeme',
      'totalContractValue': 'Toplam Sözleşme Değeri',
      'currentSponsor': 'Mevcut Sponsor',
      'replacingSponsor': 'Bu teklifi kabul etmek mevcut anlaşmayı iptal eder.',
      'offerExpiresIn': 'Teklifin geçerlilik süresi:',
      'offerExpired': 'Bu teklifin süresi doldu.',
      'acceptOffer': 'Teklifi Kabul Et',
      'acceptAndTerminate': 'Kabul Et ve Feshet',
      'insufficientBudget': 'Yetersiz Bütçe',
      'clickToView': 'Görüntülemek için tıkla',
      'reject': 'Reddet',
      'rejectAllOffers': 'Tümünü Reddet',
      'contractActive': 'Sözleşme hala devam ediyor.',
      'contractExpired': 'Sözleşme bitti. Cezai işlem olmadan yeni sponsor bulabilirsiniz.',
      'contractEndsIn': 'Kalan Süre',
      'expired': 'Süresi Doldu',
      'terminationFee': 'Fesih Bedeli',
      'terminationFeeDescription': 'Erken fesih için kalan sözleşme bedelini ödemelisiniz.',
      'year': 'yıl',
      // Sponsorships
      'sponsorships': 'Sponsorluklar',
      'sponsorshipsDescription': 'Sponsorluk anlaşmalarını yönet ve fırsatları keşfet',
      'sponsorshipsMenuDescription': 'Sponsorluk yönetimi',
      'viewSponsorships': 'Anlaşmaları Görüntüle',
      'activeSponsorships': 'Aktif Sponsorluklar',
      'active': 'Aktif',
      'selectSponsor': 'Sponsor Seç',
      'alreadyActive': 'Zaten Aktif',
      'estimatedValue': 'Tahmini Değer',
      'generateNew': 'Yeni Teklif Ara',
      'selectOffer': 'Teklif Seç',
      'available': 'Mevcut',
      'offers': 'Teklif',
      'availableOffers': 'Mevcut Teklifler',
      'allOffersRejectedMessage': 'Şu an uygun teklif yok. Daha sonra tekrar kontrol edin.',
      'level': 'Seviye',
      'tier1': 'Ulusal & Orta Seviye',
      'tier2': 'Ulusal + Yarı-Global',
      'tier3': 'Global',
      'tier4': 'Prestij',
      'sponsorOffer': 'Sponsor Teklifi',
      // Sponsorship Categories
      'stadium': 'Stadyum',
      'jersey': 'Forma',
      'matchday': 'Maç Günü',
      'digital': 'Dijital',
      'stadiumSponsorships': 'Stadyum Sponsorlukları',
      'jerseySponsorships': 'Forma Sponsorlukları',
      'matchdaySponsorships': 'Maç Günü Sponsorlukları',
      'digitalSponsorships': 'Dijital Sponsorluklar',
      'totalSponsorIncome': 'Toplam Sponsor Geliri',
      'selectSponsorshipType': 'Teklifleri görmek için bir kategori seçin',
      'contractEnds': 'Sözleşme Bitişi',
      'viewContract': 'Sözleşmeyi Gör',
      'selectOneOffer': 'Aşağıdaki tekliflerden birini seçin',
      // Sponsorship Types
      'namingRights': 'İsim Hakkı',
      'vipSkybox': 'VIP Loca',
      'ledBoards': 'LED Panolar',
      'stadiumTech': 'Stadyum Teknolojisi',
      'jerseyFront': 'Göğüs Sponsoru',
      'jerseyBack': 'Sırt Sponsoru',
      'jerseySleeve': 'Kol Sponsoru',
      'trainingKit': 'Antrenman Kiti',
      'matchdayPresentation': 'Maç Sunumu',
      'officialDrink': 'Resmi İçecek',
      'officialMerchandise': 'Resmi Ürünler',
      'matchdayBroadcast': 'Yayın Sponsoru',
      'socialMedia': 'Sosyal Medya',
      'appPartnership': 'Uygulama Ortaklığı',
      'esports': 'E-Spor',
      'streamingPlatform': 'Yayın Platformu',
      // Tier Names
      'tierLocalRegional': 'Yerel/Bölgesel',
      'tierNational': 'Ulusal',
      'tierMajorNational': 'Büyük Ulusal/Uluslararası',
      'tierInternational': 'Uluslararası',
      'tierPremiumInternational': 'Premium Uluslararası',
      'tierWorldClass': 'Dünya Markası',
      'tier': 'Seviye',
      // Squad View
      'availableFunds': 'Kasa',
      'stadiumCapacityLimitReached': 'Stadyum maksimum kapasitede. Artık büyüme prestijle olur, boyutla değil.',
      'unableToExpandStadium': 'Stadyum genişletilemiyor.',
      // Negotiation Modal
      'negotiationsFailed': 'Müzakereler Başarısız',
      'clubPulledOutOfTalks': 'Kulüp masadan kalktı.',
      'walkAway': 'Masadan Kalk',
      'accept': 'Kabul Et',
      'completeTransfer': 'Transferi Tamamla',
      'season': 'Sezon',
      'standings': 'Puan Durumu',
      'latestResults': 'Son Sonuçlar',
      'leagueStats': 'LİG İSTATİSTİKLERİ',
      'fixtures': 'FİKSTÜR',
      'seasonSummary': 'SEZON ÖZETİ',
      'played': 'O',
      'won': 'G',
      'drawn': 'B',
      'lost': 'M',
      'goalsFor': 'A',
      'goalsAgainst': 'Y',
      'goalDifference': 'AV',
      'current': 'Mevcut',
      'currentWeek': 'Bu Hafta',
      'transferWindow': 'Transfer Dönemi',
      'transferWindowNoMatches': 'Transfer Dönemi - Maç Yok',
      'you': 'Sen',
      'next': 'Sıradaki',
      'inspect': 'İncele',
      'topScorers': 'Gol Krallığı',
      'topAssists': 'Asist Krallığı',
      'referee': 'Hakem',
      'noGoalsYet': 'Henüz gol yok',
      'noAssistsYet': 'Henüz asist yok',
      'discipline': 'Disiplin',
      'winStreaks': 'Galibiyet Serileri',
      'unbeatenStreaks': 'Yenilmezlik Serileri',
      'squadValue': 'KADRO DEĞERİ',
      'wins': 'Galibiyet',
      'unbeaten': 'Yenilmezlik',
      'noCardsYet': 'Henüz kart yok',
      // Months
      'month.jan': 'Oca',
      'month.feb': 'Şub',
      'month.mar': 'Mar',
      'month.apr': 'Nis',
      'month.may': 'May',
      'month.jun': 'Haz',
      'month.jul': 'Tem',
      'month.aug': 'Ağu',
      'month.sep': 'Eyl',
      'month.oct': 'Eki',
      'month.nov': 'Kas',
      'month.dec': 'Ara',
      // Positions
      'position.GK': 'KL',
      'position.LB': 'SLB',
      'position.CB': 'STP',
      'position.RB': 'SĞB',
      'position.LWB': 'SLKB',
      'position.RWB': 'SĞKB',
      'position.CDM': 'MDO',
      'position.CM': 'MO',
      'position.CAM': 'OOS',
      'position.LM': 'SOL',
      'position.RM': 'SĞL',
      'position.LW': 'SLK',
      'position.RW': 'SĞK',
      'position.CF': 'SF',
      'position.ST': 'ST',
      // Retirement
      'retirementWarning': 'Emeklilik Kararları',
      'retirementWarningDescription': 'Bazı oyuncular sezon sonu futbolu bırakmayı düşünüyor.',
      'retirementMessage': '{name} sezon sonu emekli olmayı planlıyor.',
      'persuadeToContinue': '1 Yıl Daha Kalmaya İkna Et',
      'respectDecision': 'Karara Saygı Duy',
      'processing': 'İşleniyor...',
      'retirementAnnounced': 'Emeklilik Duyuruldu',
      'playerRetiring': 'Oyuncu Emekli Oluyor',
      'injured': 'Sakat',
      'ill': 'Hasta',
      'suspended': 'Cezalı',
      'weekOut': 'hafta yok',
      'weeksOut': 'hafta yok',
      'game': 'maç',
      'games': 'maç',
      'contractStatus': 'Sözleşme',
      'weeklyWage': 'Haftalık Maaş',
      'duration': 'Süre',
      'releaseClause': 'Serbest Kalma',
      'none': 'Yok',
      'pendingTransfer': 'Transfer Bekleniyor',
      'willJoinInWeek': 'haftaya katılacak',
      'inWeek': 'Hafta',
      'fee': 'Bedel',
      'seasonStatistics': 'Sezon İstatistikleri',
      'cards': 'Kartlar',
      'currentAbility': 'Mevcut Yetenek',
      'matchPerformanceHistory': 'Form Durumu',
      'opponent': 'Rakip',
      'result': 'Sonuç',
      'passPercent': 'Pas %',
      'saves': 'Kurtarış',
      'tackles': 'Top Çalma',
      'interceptions': 'Pas Arası',
      'minutes': 'Dakika',
      'showingLastMatches': 'Son',
      'ofMatches': 'maç',
      'matchesLower': 'maç gösteriliyor',
      'debtWarning': 'Mali Uyarı',
      'debtWarningMessage': 'Başkan Uyarıyor: Kulüp sezonu borçla kapattı.',
      'debtClearedMessage': 'Başkan borçları kapattı ancak bu tekrarlanmamalı. Gelecek sezon bütçeyi daha iyi yönetin!',
      'understood': 'Anlaşıldı',
      'gameOver': 'OYUN BİTTİ',
      'gameOverMessage': 'Yönetim görevine son verdi. Kulüp üst üste iki sezonu borçla kapattı.',
      'gameOverDescription': 'Kötü mali yönetim kovulmanıza neden oldu.',
      'backToCareerSelect': 'Kariyer Seçimine Dön',
      'back': 'Geri',
      'hasRecoveredFrom': 'iyileşti:',
      'hasSuffered': 'sakatlandı:',
      'hasContracted': 'hastalandı:',
      'outFor': 'Süre',
      'viewPerformances': 'Performansı Gör',
      // Injury Types
      'injury.hamstringstrain': 'Arka Adale Çekmesi',
      'injury.kneeligamentsprain': 'Diz Bağlarında Esneme',
      'injury.anklesprain': 'Ayak Bileği Burkulması',
      'injury.groinstrain': 'Kasık Çekmesi',
      'injury.calfstrain': 'Baldır Çekmesi',
      'injury.shoulderdislocation': 'Omuz Çıkığı',
      'injury.fracturedrib': 'Kaburga Kırığı',
      'injury.acltear': 'Ön Çapraz Bağ Yırtığı',
      'injury.mclinjury': 'İç Yan Bağ Zedelenmesi',
      'injury.achillestendonitis': 'Aşil Tendiniti',
      'injury.concussion': 'Beyin Sarsıntısı',
      'injury.backstrain': 'Bel Tutulması',
      'injury.hipflexorstrain': 'Kalça Kası Zorlanması',
      'injury.meniscustear': 'Menisküs Yırtığı',
      'injury.fracturedmetatarsal': 'Tarak Kemiği Kırığı',
      // Illness Types
      'illness.flu': 'Grip',
      'illness.foodpoisoning': 'Gıda Zehirlenmesi',
      'illness.viralinfection': 'Viral Enfeksiyon',
      'illness.stomachbug': 'Mide Üşütmesi',
      'illness.respiratoryinfection': 'Solunum Yolu Enfeksiyonu',
      'illness.fever': 'Yüksek Ateş',
      'illness.bronchitis': 'Bronşit',
      'illness.pneumonia': 'Zatürre',
      'illness.mononucleosis': 'Öpücük Hastalığı',
      'illness.migraine': 'Migren',
      // Match Screen
      'matchFeed': 'Canlı Anlatım',
      'live': 'CANLI',
      'waitingForKickoff': 'Başlama vuruşu bekleniyor...',
      'matchFinished': 'MAÇ SONA ERDİ',
      'liveMatchday': 'MAÇ GÜNÜ',
      'continueMatch': 'DEVAM ET',
      'home': 'Ev Sahibi',
      'away': 'Deplasman',
      'matchStats': 'Maç İstatistikleri',
      'matches': 'Maç',
      'shots': 'Şut',
      'possession': 'Topla Oynama',
      'assistantManager': 'Yardımcı Antrenör',
      'askAdvice': 'Tavsiye İste',
      'thinking': 'Analiz ediyor...',
      'assistantWatching': 'Maçı izliyorum patron. Müdahale etmemi istersen söyle.',
      'matchIntroTitle': 'Maç Önü',
      'matchIntroSubtitle': '{homeTeam} - {awayTeam}',
      'matchIntroDetails': '{competition} • {weekNumber}. Hafta',
      'startMatch': 'Maçı Başlat',
      'versus': 'VS',
      'kickoff': 'Başlama',
      'firstHalf': 'İlk Yarı',
      'secondHalf': 'İkinci Yarı',
      'halftime': 'Devre Arası',
      'resumeMatch': 'Maça Dön',
      'matchSummary': 'Maç Özeti',
      'homeTeam': 'Ev Sahibi',
      'awayTeam': 'Deplasman',
      'shotsOnTarget': 'İsabetli Şut',
      'corners': 'Korner',
      'fouls': 'Faul',
      'yellowCards': 'Sarı Kart',
      'redCards': 'Kırmızı Kart',
      'speed1x': 'Hız 1x',
      'speed3x': 'Hız 3x',
      'skipToEnd': 'Sonuca Atla',
      'skip': 'Atla',
      'goals': 'Goller',
      'assists': 'Asistler',
      'assistLabel': 'Asist',
      'ratingHeader': 'Puan',
      'halfTimeTitle': 'Devre Arası',
      'halfTimeResumeIn': 'İkinci yarı birazdan başlayacak',
      'seconds': 'sn',
      // Loading Messages
      'loadingCareer': 'Kariyer yükleniyor...',
      'initializingDatabase': 'Lig veritabanı hazırlanıyor...',
      'negotiatingContract': '{teamName} ile görüşülüyor...',
      'scoutingPlayers': '{teamName} için oyuncu aranıyor...',
      'simulatingDeadlineDay': 'Transferin son günü simüle ediliyor...',
      'simulatingRemainder': 'Sezonun kalanı simüle ediliyor...',
      'finalizingPreSeason': 'Sezon öncesi hazırlıklar tamamlanıyor...',
      'pause': 'DURAKLAT',
      'resume': 'DEVAM ET',
      'finishMatch': 'MAÇI BİTİR',
      'returnToMenu': 'Menüye Dön',
      'goalFor': 'GOL',
      'fullTime': 'MAÇ BİTTİ! Hakem son düdüğü çaldı.',
      'welcomeMatch': "Bugünkü karşılaşmaya hoş geldiniz! {homeTeam} - {awayTeam}. Atmosfer harika.",
      'playerPerformances': 'Oyuncu Performansları',
      'performanceDataNotAvailable': 'Bu maç için veri yok.',
      // Team Selection
      'selectClub': 'TAKIM SEÇ',
      'chooseYourLegacy': 'Hikayeni seç.',
      'budget': 'Bütçe',
      'backToTeams': 'Takımlara Dön',
      'startingBudget': 'BAŞLANGIÇ BÜTÇESİ',
      'players': 'Oyuncular',
      'formation': 'Diziliş',
      'attackRating': 'Hücum',
      'defenseRating': 'Savunma',
      'midfieldRating': 'Orta Saha',
      'overallRating': 'Genel',
      'fullSquad': 'Tüm Kadro',
      'startingXIAndTactics': 'İlk 11 ve Taktik',
      'opponentSquad': 'Rakip Kadro',
      'scout': 'İzle',
      'scouting': 'İzleniyor...',
      'approach': 'Teklif Yap',
      'view': 'Görüntüle',
      // Stadium Expansion
      'expandStadium': 'Stadyumu Büyüt',
      'startExpansion': 'İnşaatı Başlat',
      'weeks': 'hafta',
      // Match Detail Modal
      'matchweek': 'Hafta',
      'manOfTheMatch': 'Maçın Adamı',
      'manOfTheMatchAuto': 'Maçın adamı bitiş düdüğüyle seçilecek.',
      'premierLeague': 'Lig',
      // Overall Rating
      'overallRatingShort': 'GEN', // OVR/ORT yerine GEN (Genel) daha yaygın
      // Captain
      'captain': 'Kaptan',
      'setAsCaptain': 'Kaptan Yap',
      'currentCaptain': 'Mevcut Kaptan',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    // Load from localStorage or default to 'en'
    try {
      const saved = localStorage.getItem('gameLanguage') as Language;
      return saved && (saved === 'en' || saved === 'tr') ? saved : 'en';
    } catch (e) {
      console.warn('[Storage] Failed to access localStorage for gameLanguage:', e);
      return 'en';
    }
  });
  const [languageSelected, setLanguageSelected] = useState(() => {
    // Check if language was previously selected
    try {
      return localStorage.getItem('gameLanguage') !== null;
    } catch (e) {
      console.warn('[Storage] Failed to access localStorage for gameLanguage check:', e);
      return false;
    }
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem('gameLanguage', lang);
      setLanguageSelected(true);
    } catch (e) {
      console.warn('[Storage] Failed to save gameLanguage to localStorage:', e);
      // Still set the state even if storage fails
      setLanguageSelected(true);
    }
  };

  const t = (key: string, params?: Record<string, string>): string => {
    let translation = translations[language][key] || key;
    // Replace placeholders like {teamName} with actual values
    if (params) {
      Object.keys(params).forEach(param => {
        translation = translation.replace(`{${param}}`, params[param]);
      });
    }
    return translation;
  };

  // Helper function to translate positions
  const translatePosition = (position: string): string => {
    const positionKey = `position.${position}`;
    return translations[language][positionKey] || position;
  };

  // Helper function to format date with translated month
  const formatDate = (date: Date): string => {
    const monthKey = `month.${date.toLocaleDateString('en-US', { month: 'short' }).toLowerCase()}`;
    const month = translations[language][monthKey] || date.toLocaleDateString('en-US', { month: 'short' });
    const day = date.getDate();
    const year = date.getFullYear();
    return `${month} ${day}, ${year}`;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, translatePosition, formatDate, languageSelected, setLanguageSelected }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

